/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "claves.h"

bool_t
xdr_Coord (XDR *xdrs, Coord *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Tupla (XDR *xdrs, Tupla *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, MAX_STR))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, MAX_VEC,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_Coord (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TuplaRet (XDR *xdrs, TuplaRet *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, MAX_STR))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, MAX_VEC,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_Coord (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
