/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVES_H_RPCGEN
#define _CLAVES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_STR 256
#define MAX_VEC 32

struct Coord {
	int x;
	int y;
};
typedef struct Coord Coord;

struct Tupla {
	int key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	Coord value3;
};
typedef struct Tupla Tupla;

struct TuplaRet {
	int result;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	Coord value3;
};
typedef struct TuplaRet TuplaRet;

#define CLAVES_PROG 0x20000001
#define CLAVES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DESTROY 1
extern  int * destroy_1(void *, CLIENT *);
extern  int * destroy_1_svc(void *, struct svc_req *);
#define SET_VALUE 2
extern  int * set_value_1(Tupla *, CLIENT *);
extern  int * set_value_1_svc(Tupla *, struct svc_req *);
#define GET_VALUE 3
extern  TuplaRet * get_value_1(int *, CLIENT *);
extern  TuplaRet * get_value_1_svc(int *, struct svc_req *);
#define DELETE_KEY 4
extern  int * delete_key_1(int *, CLIENT *);
extern  int * delete_key_1_svc(int *, struct svc_req *);
#define MODIFY_VALUE 5
extern  int * modify_value_1(Tupla *, CLIENT *);
extern  int * modify_value_1_svc(Tupla *, struct svc_req *);
#define EXIST 6
extern  int * exist_1(int *, CLIENT *);
extern  int * exist_1_svc(int *, struct svc_req *);
extern int claves_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DESTROY 1
extern  int * destroy_1();
extern  int * destroy_1_svc();
#define SET_VALUE 2
extern  int * set_value_1();
extern  int * set_value_1_svc();
#define GET_VALUE 3
extern  TuplaRet * get_value_1();
extern  TuplaRet * get_value_1_svc();
#define DELETE_KEY 4
extern  int * delete_key_1();
extern  int * delete_key_1_svc();
#define MODIFY_VALUE 5
extern  int * modify_value_1();
extern  int * modify_value_1_svc();
#define EXIST 6
extern  int * exist_1();
extern  int * exist_1_svc();
extern int claves_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Coord (XDR *, Coord*);
extern  bool_t xdr_Tupla (XDR *, Tupla*);
extern  bool_t xdr_TuplaRet (XDR *, TuplaRet*);

#else /* K&R C */
extern bool_t xdr_Coord ();
extern bool_t xdr_Tupla ();
extern bool_t xdr_TuplaRet ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVES_H_RPCGEN */
